---
# Configure access and security

- name: Configure MariaDB temporary access for Ansible mysql_user module
  file: 
    src: /etc/mysql/debian.cnf 
    dest: /root/.my.cnf 
    owner: root 
    group: root 
    state: link 
    force: yes

- name: Set MariaDB root password for local login
  mysql_user: 
    name: root 
    password: "{{ galera_root_password }}"
    host: localhost 
    state: present

- name: Set MariaDB debian-sys-maint password for service control
  mysql_user: 
    name: debian-sys-maint 
    password: "{{ galera_maintenance_password }}"
    host: localhost 
    state: present

- name: Configure MariaDB root defaults-file
  template: 
    src: root/my.cnf.j2 
    dest: /root/.my.cnf 
    owner: root 
    group: root 
    mode:  0640 
    force: yes

- name: Configure defaults-file for debian-sys-maint service user
  template: 
    src: debian.cnf.j2 
    dest: /etc/mysql/debian.cnf 
    owner: root 
    group: root 
    mode: 0640


- name: remove test database
  mysql_db:
    name: test
    state: absent

- name: deny anonymous access
  mysql_user:
    name: ""
    state: absent

- name: remove special root access
  mysql_user:
    name: root
    host: "{{ ansible_hostname }}"
    state: absent

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ galera_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: create monitoring user
  mysql_user:
    name: "{{ galera_monitoring_user }}"
    host: '%'
    password: "{{ galera_monitoring_user_password }}"
    priv: "*.*:USAGE"
    state: present

#- name: create app user
#  mysql_user:
#    name: "{{ galera_app_user }}"
#    host: '%'
#    password: "{{ galera_app_user_password }}"
#    priv: "{{ galera_app_user_priv }}"
#    state: present


