---

- include: galera_install.yml
  when:
    ansible_distribution == 'Ubuntu'
    and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [installation]

- include: galera_rollback.yml
  when:
    ansible_distribution == 'Ubuntu'
    and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [rollback]

- include: galera_testing.yml
  when:
    ansible_distribution == 'Ubuntu'
    and (ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial')
  tags: [testing]


- meta: flush_handlers
